### ISSUE TITLE
Support debug proxy?

### ISSUE THREAD

**Issue by klausenbusk** [BrianGilbert/xdebug-helper-for-firefox#1]
Hello

Do you plan on support `debug proxy`? https://derickrethans.nl/debugging-with-multiple-users.html
I need that, to work around the NAT issue.

Kristian

**Comment by klausenbusk** [comment]
Nvm, I misunderstood this project. It only start the debugger.
Sorry for the noise.

**Comment by BrianGilbert** [comment]
@klausenbusk No Problem, thanks for closing the issue :)
