### ISSUE TITLE
Hide in Page Actions or Overflow Menu

### ISSUE THREAD

**Issue by hackel** [BrianGilbert/xdebug-helper-for-firefox#2]
Thanks for porting this extension to Firefox!  I was wondering if it would be possible to move the icon that appears in the URL bar to the "page actions" menu (3 dot menu) when debugging is disabled.  Another option would be to enable the ability to "Pin to Overflow Menu" which works for other standard extension icons.

It's a minor thing but I just think it would be nice to get it out of the way when it's not in use.

**Comment by BrianGilbert** [comment]
you can do this using userChrome.css
