### ISSUE TITLE
Doesn't work on redirect

### ISSUE THREAD

**Issue by Bilge** [BrianGilbert/xdebug-helper-for-firefox#23]
If a site redirects to a location that has been configured to use the debugger, the debugger does not actually activate. For example, when debugging an OAuth flow, when the third party site redirects back to my local debugged site, the redirect back is never debugged.

**Comment by Seros** [comment]
I noticed the same behaviour and tested a different extension (https://addons.mozilla.org/en-US/firefox/addon/xdebug-ext-quantum) and it worked for the redirect. I think it's the way the cookie is set. I tested different configurations and it seems the only difference between both extension is that this extension is setting the SameSite attribute of the cookie to "Strict" though the other one is setting it to "Lax" but this is also the default value if not passed. So the "Strict" seems to break the xdebug remote debug workflow.

**Comment by Bilge** [comment]
@Seros Great write-up, I hope @BrianGilbert sees it.
