### ISSUE TITLE
How to set list of hosts, where extension will be visible?

### ISSUE THREAD

**Issue by MurzNN** [BrianGilbert/xdebug-helper-for-firefox#24]
From extension description: 

> By default the extension icon will show up on all pages, but to keep your browser as clean as possible, the extension can be configured to be only visible at the pages you want in the settings panel.

But I can't find how to configure ~~whitelist~~ allowlist of hosts in settings page (moz-extension://44873113-323c-487d-a91b-b58ca3e37d94/options.html) - I see only configuration for IDE key, Trace Trigger Value, Profile Trigger Value here.

**Comment by BrianGilbert** [comment]
my current userChrome contains it https://gist.github.com/BrianGilbert/1ad7e3931406f485a86a35aefb0aa1b1
