### ISSUE TITLE
Don't rely exclusively on color for icon status

### ISSUE THREAD

**Issue by mattschlosser** [BrianGilbert/xdebug-helper-for-firefox#26]
Firefox 89 has updated the UI, removing all colors from the address bar. This makes it impossible to tell the state of xdebug. Perhaps add an underline to the active icon. 

![no-green-status](https://user-images.githubusercontent.com/8870594/115589187-cc33cc80-a28c-11eb-93f7-b72bd3bed5c8.png)

**Comment by mstrelan** [comment]
FWIW the bookmark icon still has colour

**Comment by BrianGilbert** [comment]
Disabled status now shown in address bar by outline version of the ison, the disable icon has been changed to power icon
