### ISSUE TITLE
FF 57b: Icon not always shown in address bar

### ISSUE THREAD

**Issue by liayn** [BrianGilbert/xdebug-helper-for-firefox#3]
For some mysterious reason the icon of the add-on vanishes on some sites.

I could already identify one case: If the reader-mode icon is displayed by FF, the icon vanishes.
But also on pages where nothing special is happening in the address bar the icon is simply missing.

**Comment by liayn** [comment]
Maybe this check `if (!tab.url.match(/^about:/|/^moz-extension:/)) {` is in vain as the icon is visible on the `about:config` tab

**Comment by liayn** [comment]
okay... looks like the issue is that those pages which do not show the icon have a JS error in the scripts loaded by the page.
Didn't know that this kills addons....

**Comment by Polylogic** [comment]
Instead of having a single expression `/^about:|^moz-extension:/` there are two `/^about:/ | /^moz-extension:/`

**Comment by liayn** [comment]
True, I'm not even sure if the current syntax is valid at all.
The issue still seems to be related to JS errors on the currently visited website.

**Comment by BrianGilbert** [comment]
I have seen the issue with the icon dissapearing on some pages as well. Not sure this will fix it, but it at least fixes display on about:  1.0.5 release uploaded to extensions site.

Will leave issue open until I get some confirmation about the not always showing issue.

**Comment by Polylogic** [comment]
Works well for me.

**Comment by BrianGilbert** [comment]
@Polylogic does that seem to have fixed the intermittent icon on real pages?

**Comment by liayn** [comment]
How can I test that? is there a nightly build or so?

**Comment by BrianGilbert** [comment]
@liayn just check for extension updates, it's already live..

**Comment by liayn** [comment]
oh nice. works good so far. thanks!

**Comment by Polylogic** [comment]
@BrianGilbert This issue is fixed. Thanks.
Neat webext replacement for "The easiest Xdebug"

**Comment by BrianGilbert** [comment]
@Polylogic thanks, closing issue.
