### ISSUE TITLE
Add `settings` button.

### ISSUE THREAD

**Issue by Strongleong** [BrianGilbert/xdebug-helper-for-firefox#35]
To go to the settings in Firefox I need to manually insert url like `moz-extension://{extension-id}/options.html`. It would be nice if I haven't need to do this.

**Comment by MagicLegend** [comment]
For me the keyboard shortcuts very rarely work, but you can access the settings also from `about:addons`:

![image](https://user-images.githubusercontent.com/3169104/174481685-a91e5b4f-05fe-4319-826c-419e190711e7.png)

And then `Preferences` will land you at `/options.html` as well.

**Comment by BrianGilbert** [comment]
Settings link is available in xdebug popup in version 1.0.10
