### ISSUE TITLE
Provide new version of master code on addons.mozilla.org

### ISSUE THREAD

**Issue by das-peter** [BrianGilbert/xdebug-helper-for-firefox#36]
Yesterday out of the blue the current version (1.0.6) available here https://addons.mozilla.org/de/firefox/addon/xdebug-helper-for-firefox/ stopped working.
I then made a quick test if the code from this repository would work and it did.
Current assumption is that the fix #23 made it work again.

Now, unfortunately it is not possible to install an unsigned add-on anymore even with signature check off in `about:config`.
Hence I kindly request an update of the extension available on addons.mozilla.org

Thank you very much in advance.

Best Regards,
Peter

**Comment by BrianGilbert** [comment]
resolved 1.0.9 approved last week, 1.0.10 pending review at the moment.
