### ISSUE TITLE
Icon not available on localhost

### ISSUE THREAD

**Issue by piRGoif** [BrianGilbert/xdebug-helper-for-firefox#4]
I can't see the icon when browsing on http://localhost URL... It's too bad cause it's the main domain where I use xdebug...

**Comment by CLINT0N** [comment]
It also does not appear on local .dev domains. Is it not possible to just make it appear for everything?

**Comment by BrianGilbert** [comment]
.dev is a real TLD and you shouldn't use it for local dev, it's far better to use .local which I can confirm works.

https://iyware.com/dont-use-dev-for-development/

**Comment by jnachtigall** [comment]
nitpicking: fwiw, I think it's actually .test domain for what many people use .dev for (i think .local is also not officially for this, whereas .test i)

**Comment by guedressel** [comment]
I suggest to not use .local either. It's used by mDNS - see https://en.wikipedia.org/wiki/.local

Best bet is .localhost

**Comment by BrianGilbert** [comment]
confirmed working with .localhost
