### ISSUE TITLE
your icons dont match and it is confusing

### ISSUE THREAD

**Issue by shoulders** [BrianGilbert/xdebug-helper-for-firefox#40]
the icon in the toolbar is 

![image](https://user-images.githubusercontent.com/319997/180770680-8d11e10d-6404-4386-9543-dc938c148784.png)

the icon in the extensions area is

![image](https://user-images.githubusercontent.com/319997/180770730-45c0a9f8-4c5e-47a6-a171-629c7667419b.png)

Can you make them match. The one on an angle is more unique.

**Comment by BrianGilbert** [comment]
The toolbar icon is now monotone.
