### ISSUE TITLE
[firefox] debug icon not change color by click

### ISSUE THREAD

**Issue by ESCA7A** [BrianGilbert/xdebug-helper-for-firefox#41]
icon always is white
Firefox v: 103.0.2
- [https://ibb.co/71hdYQj](url) 
- [https://ibb.co/m9HSjsc](url)

**Comment by ESCA7A** [comment]
[url=https://ibb.co/71hdYQj][img]https://i.ibb.co/sV7dmCb/Screenshot-at-2022-08-19-14-11-56.png[/img][/url]
[url=https://ibb.co/m9HSjsc][img]https://i.ibb.co/qNRxSGr/Screenshot-at-2022-08-19-14-12-10.png[/img][/url]

**Comment by ESCA7A** [comment]
- https://postimg.cc/jWBRmjNr
- https://postimg.cc/xN2njFtx

**Comment by EvoWebFrance** [comment]
Perhaps change the the Icon when in debug mode : pest control
The icon is slightly different

**Comment by BrianGilbert** [comment]
Address bar icon changes from outline to solid version since v1.0.9. outline = disabled
