### ISSUE TITLE
No longer works with latest Firefox (112)

### ISSUE THREAD

**Issue by JimBacon** [BrianGilbert/xdebug-helper-for-firefox#43]
Enabling debug mode creates a cookie which is deleted again moments later, effectively disabling it. You can see the cookie appear and disappear in the Firefox Developer tools on the Storage tab.

Experienced with Firefox 112.0.1-1 on Ubuntu 22.04.2 installed by snap.

Revert to Firefox 102.10.0esr (64 bit) and it works again.

**Comment by BrianGilbert** [comment]
I'm using this with Nightly nearly every day, it definitely still works here.
