### ISSUE TITLE
Can't read and change data on this site

### ISSUE THREAD

**Issue by theking2** [BrianGilbert/xdebug-helper-for-firefox#44]
The plugin shows
![image](https://github.com/BrianGilbert/xdebug-helper-for-firefox/assets/1612152/2c1f42c0-6743-4291-94fd-bbe5e7e420d2)

and is not working

**Comment by theking2** [comment]
At the bottom I see this:
![image](https://github.com/BrianGilbert/xdebug-helper-for-firefox/assets/1612152/94a8e5bd-b753-435c-be01-a4d58d94976a)

**Comment by BrianGilbert** [comment]
@theking2 you operate this addon from the icon in the address bar, not the addon's popup menu. If it's not working you have a configuration issue on your webserver or in your IDE, I'm using it daily, and know of many others also doing the same.

![xdebug-helper-for-firefox 2023-07-20 08-42-52](https://github.com/BrianGilbert/xdebug-helper-for-firefox/assets/114017/4cafb056-3836-4520-bf8d-4db3a175130c)
