### ISSUE TITLE
Cannot open extension in Firefox

### ISSUE THREAD

**Issue by familieslifedev** [BrianGilbert/xdebug-helper-for-firefox#45]
<img width="439" alt="Screenshot 2023-07-19 at 08 48 43" src="https://github.com/BrianGilbert/xdebug-helper-for-firefox/assets/139958469/024e8a49-6f60-48e8-a45e-858f6f00ce11">
The extension is constantly greyed out on Firefox and cannot be selected or added to the toolbar. This makes the extension fully unusable. I've tried using it in a different version of Firefox (Dev Edition instead of Release) and the issue still persisted. This issue is only present in Firefox and the extension seems to work fine in Chrome and Edge.

**Comment by BrianGilbert** [comment]
In case anyone else has this problem.. You do not interact with it from that icon, there should be a bug icon on your address bar that you operate it via.
![xdebug-helper-for-firefox 2023-07-20 08-42-52](https://github.com/BrianGilbert/xdebug-helper-for-firefox/assets/114017/147869c0-cfc3-4600-aaee-5cf3df25a0f1)
