### ISSUE TITLE
Incorrect icon displays after page refresh

### ISSUE THREAD

**Issue by mstrelan** [BrianGilbert/xdebug-helper-for-firefox#46]
Very happy to see the new icon. It works well when toggling debugging on and off, but after reloading the page I always see the default icon. Using version 1.0.9 on Firefox 115.0.2.

**Comment by BrianGilbert** [comment]
I'm unable to replicate this on FF Nightly, if I reload with xdebug enabled the icon displayed for me is the solid version.

Can you point me to a replicate-able example site?

**Comment by mstrelan** [comment]
You're right, it works fine on Nightly (117.0a1). Not sure then if it's a 115 problem or something with my user profile.

**Comment by mstrelan** [comment]
After disabling and enabling a bunch of extensions it's working correctly now on 115. Sorry for the noise.

**Comment by BrianGilbert** [comment]
@mstrelan all good, it resulted in your issue being resolved 👍
