### ISSUE TITLE
Icon fails to show status in view-source:

### ISSUE THREAD

**Issue by Roy-Orbison** [BrianGilbert/xdebug-helper-for-firefox#5]
When using `view-source:`, the icon does not correctly show the status for that domain, nor appear to toggle state when clicked. However, the request still triggers debugging when loading a page in that view, if it's already been enabled for the domain.

**Comment by Roy-Orbison** [comment]
Showing now, but always has the disabled state icon.

**Comment by BrianGilbert** [comment]
> Showing now, but always has the disabled state icon.

At least one other user had this caused by one of their other existing extensions, I am using Nightly and it's working fine.

See https://github.com/BrianGilbert/xdebug-helper-for-firefox/issues/46

**Comment by Roy-Orbison** [comment]
Seems to be okay now. I didn't make any changes to try to make it work. :shrug:
