### ISSUE TITLE
Firefox Extensions only shows version 1.0.5

### ISSUE THREAD

**Issue by marcvangend** [BrianGilbert/xdebug-helper-for-firefox#6]
I'm trying to install Xdebug-helper, but it seems that I can only install version 1.0.5, which is not compatible with FF57. Looking at https://github.com/BrianGilbert/xdebug-helper-for-firefox/releases, version 1.6.1 should be the latest stable, right? I'm using Firefox 57.0 on macOS Sierra.

![screen shot 2017-11-14 at 10 48 50](https://user-images.githubusercontent.com/315224/32773448-7ef6eb0e-c929-11e7-931f-2cb44eda7072.png)

**Comment by BBGuy** [comment]
Having the same issue

**Comment by lllopo** [comment]
Same for me.

**Comment by hedrickbt** [comment]
I am seeing the issue as well.

**Comment by oopen** [comment]
Same, need to use [WebExtension](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Anatomy_of_a_WebExtension) only

**Comment by AlexandreBonneau** [comment]
ditto with Firefox `59.0b1`

**Comment by BrianGilbert** [comment]
if you look at th source code you can see that the current version is 1.0.5

**Comment by AlexandreBonneau** [comment]
Why is there a differences between the release versions (https://github.com/BrianGilbert/xdebug-helper-for-firefox/releases) and the `1.0.5` version?
