### ISSUE TITLE
Netbeans selection isn't saved.

### ISSUE THREAD

**Issue by kenITR** [BrianGilbert/xdebug-helper-for-firefox#9]
On Firefox 59 on Fedora, the IDE key selection of Netbeans is not kept between sessions.

**Comment by BrianGilbert** [comment]
is this still an issue?

**Comment by KacerCZ** [comment]
I found this issue in Firefox 80.0.1 on Linux in private mode.
Any change to IDE key made in private mode is not saved.
If you change IDE key in normal mode and then open private mode, then IDE key is still Eclipse and not key set in normal mode.

**Comment by BrianGilbert** [comment]
this seems like a browser issue.
